In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.feature_selection import RFE

from sklearn.datasets import make_classification
from sklearn.neighbors import KNeighborsClassifier

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

In [2]:
covid = pd.read_csv('dataset/owid-covid-data.csv')

The OxCGRT project calculate a Government Stringency Index, a composite measure of nine of the response metrics.

The nine metrics used to calculate the Government Stringency Index are: school closures; workplace closures; cancellation of public events; restrictions on public gatherings; closures of public transport; stay-at-home requirements; public information campaigns; restrictions on internal movements; and international travel controls.

The index on any given day is calculated as the mean score of the nine metrics, each taking a value between 0 and 100. See the authors’ full description of how this index is calculated.

A higher score indicates a stricter government response (i.e. 100 = strictest response). If policies vary at the subnational level, the index is shown as the response level of the strictest sub-region.

It’s important to note that this index simply records the strictness of government policies. It does not measure or imply the appropriateness or effectiveness of a country’s response. A higher score does not necessarily mean that a country’s response is ‘better’ than others lower on the index.

https://github.com/owid/covid-19-data/tree/master/public/data

In [3]:
covid_pol = pd.read_csv('dataset/covid-19-testing-policy.csv')

This interactive chart maps government policies on testing for COVID-19. Note that this relates to PCR testing for the virus only; it does not include non-PCR, antibody testing.

Countries are grouped into four categories:

No testing policy
Testing only for those who both (a) have symptoms AND (b) meet specific criteria (e.g. key workers, admitted to hospital, came into contact with a known case, returned from overseas)
Testing of anyone showing COVID-19 symptoms
Open public testing (e.g “drive through” testing available to asymptomatic people)

In [4]:
covid.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-03,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-04,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-05,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-06,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-07,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN

In [7]:
covid.shape

(330832, 67)

In [5]:
covid_pol.head()

        Entity Code         Day  testing_policy
0  Afghanistan  AFG  2020-01-01               0
1  Afghanistan  AFG  2020-01-02               0
2  Afghanistan  AFG  2020-01-03               0
3  Afghanistan  AFG  2020-01-04               0
4  Afghanistan  AFG  2020-01-05               0

Linear regression:
- Predict number of deaths based on certain factors - how accurate - econometrics
- Clusters
- Stringency
- Time series, outliers

Other data:
- Social media
- Education: enrollment, hsc results, completion

In [12]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(covid, test_size=0.1, random_state=142)

In [ ]:
reg = linear_model.LinearRegression()

#Creating train set for model A
Xa = train1[['category_code', 'review_code']]
ya = train1['rating']

reg.fit(Xa, ya)
print("y = x *", reg.coef_, "+", reg.intercept_)

In [ ]:
predicted_traina = reg.predict(Xa)
mse_traina = ((np.array(ya)-predicted_traina)**2).sum()/len(ya)
r2_traina = r2_score(ya, predicted_traina)
print("MSE train:", mse_traina)
print("R Squared train:", r2_traina)

In [ ]:
Xc = df[['category_code', 'review_code', 'helpfulness', 'gender_code', 'item_code']]
yc = df['rating_code']

Xc.head()

lr.fit(Xc,yc)
rfe = RFE(lr)
rfe_model = rfe.fit(Xc, yc)
print("No. of features: ", rfe_model.n_features_)
print("Selected features: ", rfe_model.support_)
print("Features ranking: ", rfe_model.ranking_)

In [ ]:
from sklearn.cluster import KMeans
from sklearn.metrics import pairwise_distances
from scipy.cluster.hierarchy import linkage, dendrogram, cut_tree
from scipy.spatial.distance import pdist 
from sklearn.feature_extraction.text import TfidfVectorizer
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
km2 = KMeans(n_clusters = 2)
pokemon2 = pokemon

km2.fit(pokemon2)

pokemon2['label'] = km.predict(pokemon2)

c_means = pokemon2.groupby(['label']).agg('mean')
c_means

In [ ]:
plt.scatter(pokemon2['Attack'], pokemon2['Defense'], c = pokemon2['label'])

In [ ]:
dist_poke = pdist(pokemon, 'euclidean')

dist_poke

linkage_poke = linkage(dist_poke, method = 'complete')

linkage_poke

plt.figure(figsize =(18,12))

dendrogram(linkage_poke)

plt.show()

In [ ]:
vectorizer = TfidfVectorizer(max_features = 50)

X = vectorizer.fit_transform(books.summary).toarray()

print(vectorizer.get_feature_names())